/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteRouteImport } from './routes/$locale/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleServicosRouteImport } from './routes/$locale/servicos'
import { Route as LocaleQuemSomosRouteImport } from './routes/$locale/quem-somos'
import { Route as LocaleProdutosRouteImport } from './routes/$locale/produtos'
import { Route as LocaleHomeRouteImport } from './routes/$locale/home'
import { Route as LocaleContactoRouteImport } from './routes/$locale/contacto'
import { Route as LocaleCaseStudiesRouteImport } from './routes/$locale/case-studies'

const LocaleRouteRoute = LocaleRouteRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleServicosRoute = LocaleServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleQuemSomosRoute = LocaleQuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleProdutosRoute = LocaleProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleHomeRoute = LocaleHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleContactoRoute = LocaleContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleCaseStudiesRoute = LocaleCaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => LocaleRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/case-studies': typeof LocaleCaseStudiesRoute
  '/$locale/contacto': typeof LocaleContactoRoute
  '/$locale/home': typeof LocaleHomeRoute
  '/$locale/produtos': typeof LocaleProdutosRoute
  '/$locale/quem-somos': typeof LocaleQuemSomosRoute
  '/$locale/servicos': typeof LocaleServicosRoute
  '/$locale/': typeof LocaleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale/case-studies': typeof LocaleCaseStudiesRoute
  '/$locale/contacto': typeof LocaleContactoRoute
  '/$locale/home': typeof LocaleHomeRoute
  '/$locale/produtos': typeof LocaleProdutosRoute
  '/$locale/quem-somos': typeof LocaleQuemSomosRoute
  '/$locale/servicos': typeof LocaleServicosRoute
  '/$locale': typeof LocaleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/case-studies': typeof LocaleCaseStudiesRoute
  '/$locale/contacto': typeof LocaleContactoRoute
  '/$locale/home': typeof LocaleHomeRoute
  '/$locale/produtos': typeof LocaleProdutosRoute
  '/$locale/quem-somos': typeof LocaleQuemSomosRoute
  '/$locale/servicos': typeof LocaleServicosRoute
  '/$locale/': typeof LocaleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/case-studies'
    | '/$locale/contacto'
    | '/$locale/home'
    | '/$locale/produtos'
    | '/$locale/quem-somos'
    | '/$locale/servicos'
    | '/$locale/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale/case-studies'
    | '/$locale/contacto'
    | '/$locale/home'
    | '/$locale/produtos'
    | '/$locale/quem-somos'
    | '/$locale/servicos'
    | '/$locale'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/case-studies'
    | '/$locale/contacto'
    | '/$locale/home'
    | '/$locale/produtos'
    | '/$locale/quem-somos'
    | '/$locale/servicos'
    | '/$locale/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRouteRoute: typeof LocaleRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/servicos': {
      id: '/$locale/servicos'
      path: '/servicos'
      fullPath: '/$locale/servicos'
      preLoaderRoute: typeof LocaleServicosRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/quem-somos': {
      id: '/$locale/quem-somos'
      path: '/quem-somos'
      fullPath: '/$locale/quem-somos'
      preLoaderRoute: typeof LocaleQuemSomosRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/produtos': {
      id: '/$locale/produtos'
      path: '/produtos'
      fullPath: '/$locale/produtos'
      preLoaderRoute: typeof LocaleProdutosRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/home': {
      id: '/$locale/home'
      path: '/home'
      fullPath: '/$locale/home'
      preLoaderRoute: typeof LocaleHomeRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/contacto': {
      id: '/$locale/contacto'
      path: '/contacto'
      fullPath: '/$locale/contacto'
      preLoaderRoute: typeof LocaleContactoRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/case-studies': {
      id: '/$locale/case-studies'
      path: '/case-studies'
      fullPath: '/$locale/case-studies'
      preLoaderRoute: typeof LocaleCaseStudiesRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
  }
}

interface LocaleRouteRouteChildren {
  LocaleCaseStudiesRoute: typeof LocaleCaseStudiesRoute
  LocaleContactoRoute: typeof LocaleContactoRoute
  LocaleHomeRoute: typeof LocaleHomeRoute
  LocaleProdutosRoute: typeof LocaleProdutosRoute
  LocaleQuemSomosRoute: typeof LocaleQuemSomosRoute
  LocaleServicosRoute: typeof LocaleServicosRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
}

const LocaleRouteRouteChildren: LocaleRouteRouteChildren = {
  LocaleCaseStudiesRoute: LocaleCaseStudiesRoute,
  LocaleContactoRoute: LocaleContactoRoute,
  LocaleHomeRoute: LocaleHomeRoute,
  LocaleProdutosRoute: LocaleProdutosRoute,
  LocaleQuemSomosRoute: LocaleQuemSomosRoute,
  LocaleServicosRoute: LocaleServicosRoute,
  LocaleIndexRoute: LocaleIndexRoute,
}

const LocaleRouteRouteWithChildren = LocaleRouteRoute._addFileChildren(
  LocaleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRouteRoute: LocaleRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
